
---

- hosts: grp1
  become: true
  tasks:
    - name: Lamp install
      yum: name={{item}} state=installed disable_gpg_check=yes
      with_items:
              - httpd
              - php
              - mariadb
              - php-mysql
              - mariadb-server
      register: Lampstatus

    - name: starting lamp services
      service: name={{item}} enabled=yes state=started
      with_items:
              - mariadb
              - httpd
      when: Lampstatus|success
